# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\gui\template\actualizar_ultimo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

from app.iris.rest_iris import RestIris

class Ui_DialogActualizarUltimo(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 436)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 451, 251))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBoxSPL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPL.setFont(font)
        self.spinBoxSPL.setObjectName("spinBoxSPL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPL)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBoxSPW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPW.setFont(font)
        self.spinBoxSPW.setObjectName("spinBoxSPW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPW)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinBoxPTL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTL.setFont(font)
        self.spinBoxPTL.setObjectName("spinBoxPTL")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTL)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBoxPTW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTW.setFont(font)
        self.spinBoxPTW.setObjectName("spinBoxPTW")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTW)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEditSpecies = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditSpecies.setFont(font)
        self.lineEditSpecies.setObjectName("lineEditSpecies")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditSpecies)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(230, 30, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButtonAceptar = QtWidgets.QPushButton(Dialog)
        self.pushButtonAceptar.setGeometry(QtCore.QRect(370, 370, 93, 28))
        self.pushButtonAceptar.setObjectName("pushButtonAceptar")
        self.pushButtonLimpiar = QtWidgets.QPushButton(Dialog)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(260, 370, 93, 28))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.textEditRespuesta = QtWidgets.QTextEdit(Dialog)
        self.textEditRespuesta.setGeometry(QtCore.QRect(490, 100, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEditRespuesta.setFont(font)
        self.textEditRespuesta.setObjectName("textEditRespuesta")

        self.pushButtonAceptar.clicked.connect(self.aceptar)
        self.pushButtonLimpiar.clicked.connect(self.limpiar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def limpiar(self):
        self.lineEditSpecies.clear()
        self.spinBoxSPL.setValue(0)
        self.spinBoxSPW.setValue(0)
        self.spinBoxPTL.setValue(0)
        self.spinBoxPTW.setValue(0)
        self.textEditRespuesta.clear()
        self.textEditRespuesta.setText("{}")

    def aceptar(self):
        # Get from the form
        species = self.lineEditSpecies.text()
        spl = self.spinBoxSPL.value()
        spw = self.spinBoxSPW.value()
        ptl = self.spinBoxPTL.value()
        ptw = self.spinBoxPTW.value()
        # Create a dictionary with the data
        data = {
            "species": species,
            "sepal_length": spl,
            "sepal_width": spw,
            "petal_length": ptl,
            "petal_width": ptw
        }
        iris = RestIris()
        response = iris.put_last_row(data)
        self.textEditRespuesta.setText(json.dumps(response, indent=4))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Sepal Length (cm):"))
        self.label_11.setText(_translate("Dialog", "Sepal Width (cm):"))
        self.label_8.setText(_translate("Dialog", "Petal Length (cm):"))
        self.label_9.setText(_translate("Dialog", "Petal Width (cm):"))
        self.label_10.setText(_translate("Dialog", "Species:"))
        self.label_12.setText(_translate("Dialog", "Actualizar Última Fila"))
        self.pushButtonAceptar.setText(_translate("Dialog", "Aceptar"))
        self.pushButtonLimpiar.setText(_translate("Dialog", "Limpiar"))
        self.textEditRespuesta.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">{}</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DialogActualizarUltimo()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
