# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\gui\template\actualizar_id.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from app import RestIris
import json

class Ui_DialogActualizarPorID(object):
    def setupUi(self, DialogActualizarPorID):
        DialogActualizarPorID.setObjectName("DialogActualizarPorID")
        DialogActualizarPorID.resize(724, 480)
        self.label_28 = QtWidgets.QLabel(DialogActualizarPorID)
        self.label_28.setGeometry(QtCore.QRect(280, 40, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.pushButtonLimpiar = QtWidgets.QPushButton(DialogActualizarPorID)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(270, 400, 93, 28))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.pushButtonAceptar = QtWidgets.QPushButton(DialogActualizarPorID)
        self.pushButtonAceptar.setGeometry(QtCore.QRect(380, 400, 93, 28))
        self.pushButtonAceptar.setObjectName("pushButtonAceptar")
        self.formLayoutWidget_3 = QtWidgets.QWidget(DialogActualizarPorID)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 100, 451, 281))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setVerticalSpacing(15)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.spinBoxSPL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPL.setFont(font)
        self.spinBoxSPL.setObjectName("spinBoxSPL")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPL)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.spinBoxSPW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPW.setFont(font)
        self.spinBoxSPW.setObjectName("spinBoxSPW")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPW)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.spinBoxPTL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTL.setFont(font)
        self.spinBoxPTL.setObjectName("spinBoxPTL")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTL)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.spinBoxPTW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTW.setFont(font)
        self.spinBoxPTW.setObjectName("spinBoxPTW")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTW)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEditSpecies = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditSpecies.setFont(font)
        self.lineEditSpecies.setObjectName("lineEditSpecies")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditSpecies)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.spinBoxID = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxID.setFont(font)
        self.spinBoxID.setObjectName("spinBoxID")
        self.spinBoxID.setMaximum(999999)
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBoxID)
        self.textEditRespuesta = QtWidgets.QTextEdit(DialogActualizarPorID)
        self.textEditRespuesta.setGeometry(QtCore.QRect(490, 100, 201, 281))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEditRespuesta.setFont(font)
        self.textEditRespuesta.setObjectName("textEditRespuesta")

        self.pushButtonLimpiar.clicked.connect(self.limpiar)
        self.pushButtonAceptar.clicked.connect(self.actualizar)

        self.retranslateUi(DialogActualizarPorID)
        QtCore.QMetaObject.connectSlotsByName(DialogActualizarPorID)

    def limpiar(self):
        self.spinBoxSPL.setValue(0)
        self.spinBoxSPW.setValue(0)
        self.spinBoxPTL.setValue(0)
        self.spinBoxPTW.setValue(0)
        self.spinBoxID.setValue(0)
        self.lineEditSpecies.clear()
        self.textEditRespuesta.clear()
        self.textEditRespuesta.setText("{}")

    def actualizar(self):
        spl = self.spinBoxSPL.value()
        spw = self.spinBoxSPW.value()
        ptl = self.spinBoxPTL.value()
        ptw = self.spinBoxPTW.value()
        id = self.spinBoxID.value()
        species = self.lineEditSpecies.text()
        data = {
            "sepal_length": spl,
            "sepal_width": spw,
            "petal_length": ptl,
            "petal_width": ptw,
            "species": species,
            "id": id
        }
        iris = RestIris()
        response = iris.put_by_id(data)
        self.textEditRespuesta.setText(json.dumps(response, indent=4))

    def retranslateUi(self, DialogActualizarPorID):
        _translate = QtCore.QCoreApplication.translate
        DialogActualizarPorID.setWindowTitle(_translate("DialogActualizarPorID", "Víctor Luque -PyQT5 - Actualizar por ID"))
        self.label_28.setText(_translate("DialogActualizarPorID", "Actualizar Por ID"))
        self.pushButtonLimpiar.setText(_translate("DialogActualizarPorID", "Limpiar"))
        self.pushButtonAceptar.setText(_translate("DialogActualizarPorID", "Aceptar"))
        self.label_23.setText(_translate("DialogActualizarPorID", "Sepal Length (cm):"))
        self.label_24.setText(_translate("DialogActualizarPorID", "Sepal Width (cm):"))
        self.label_25.setText(_translate("DialogActualizarPorID", "Petal Length (cm):"))
        self.label_26.setText(_translate("DialogActualizarPorID", "Petal Width (cm):"))
        self.label_27.setText(_translate("DialogActualizarPorID", "Species:"))
        self.label_29.setText(_translate("DialogActualizarPorID", "ID:"))
        self.textEditRespuesta.setHtml(_translate("DialogActualizarPorID", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">{}</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogActualizarPorID = QtWidgets.QDialog()
    ui = Ui_DialogActualizarPorID()
    ui.setupUi(DialogActualizarPorID)
    DialogActualizarPorID.show()
    sys.exit(app.exec_())
