# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\gui\template\eliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from app import RestIris

class Ui_DialogEliminar(object):
    def setupUi(self, DialogDelete):
        DialogDelete.setObjectName("DialogDelete")
        DialogDelete.resize(507, 172)
        self.pushButtonEliminarPorID = QtWidgets.QPushButton(DialogDelete)
        self.pushButtonEliminarPorID.setGeometry(QtCore.QRect(280, 120, 93, 28))
        self.pushButtonEliminarPorID.setObjectName("pushButton")
        self.pushButtonEliminarUltimaFila = QtWidgets.QPushButton(DialogDelete)
        self.pushButtonEliminarUltimaFila.setGeometry(QtCore.QRect(140, 120, 131, 28))
        self.pushButtonEliminarUltimaFila.setObjectName("pushButton_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(DialogDelete)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(140, 70, 231, 41))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setVerticalSpacing(15)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBoxID = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBoxID.setMaximum(999999)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxID.setFont(font)
        self.spinBoxID.setObjectName("spinBoxSPL_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxID)
        self.label_8 = QtWidgets.QLabel(DialogDelete)
        self.label_8.setGeometry(QtCore.QRect(200, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.pushButtonEliminarPorID.clicked.connect(self.eliminarPorID)
        self.pushButtonEliminarUltimaFila.clicked.connect(self.eliminarUltimaFila)

        self.retranslateUi(DialogDelete)
        QtCore.QMetaObject.connectSlotsByName(DialogDelete)

    def eliminarPorID(self):
        id = self.spinBoxID.value()
        iris = RestIris()
        iris.delete_by_id({"id": id})
        self.spinBoxID.setValue(0)

    def eliminarUltimaFila(self):
        iris = RestIris()
        iris.delete_last_row()

    def retranslateUi(self, DialogDelete):
        _translate = QtCore.QCoreApplication.translate
        DialogDelete.setWindowTitle(_translate("DialogDelete", "Víctor Luque - PyQT5 - Eliminar"))
        self.pushButtonEliminarPorID.setText(_translate("DialogDelete", "Eliminar por ID"))
        self.pushButtonEliminarUltimaFila.setText(_translate("DialogDelete", "Eliminar última Fila"))
        self.label_7.setText(_translate("DialogDelete", "ID:"))
        self.label_8.setText(_translate("DialogDelete", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogDelete = QtWidgets.QDialog()
    ui = Ui_DialogEliminar()
    ui.setupUi(DialogDelete)
    DialogDelete.show()
    sys.exit(app.exec_())
