# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\gui\template\insertar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from app import RestIris

class Ui_DialogInsertar(object):
    def setupUi(self, DialogInsertar):
        DialogInsertar.setObjectName("DialogInsertar")
        DialogInsertar.resize(715, 417)
        DialogInsertar.setToolTipDuration(5)
        self.formLayoutWidget = QtWidgets.QWidget(DialogInsertar)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 90, 451, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBoxSPL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPL.setFont(font)
        self.spinBoxSPL.setObjectName("spinBoxSPL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPL)
        self.spinBoxSPW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPW.setFont(font)
        self.spinBoxSPW.setObjectName("spinBoxSPW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPW)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBoxPTL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTL.setFont(font)
        self.spinBoxPTL.setObjectName("spinBoxPTL")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTL)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBoxPTW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTW.setFont(font)
        self.spinBoxPTW.setObjectName("spinBoxPTW")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTW)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditSpecies = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditSpecies.setFont(font)
        self.lineEditSpecies.setObjectName("lineEditSpecies")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditSpecies)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pushButtonLimpiar = QtWidgets.QPushButton(DialogInsertar)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(250, 360, 93, 28))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.pushButtonAceptar = QtWidgets.QPushButton(DialogInsertar)
        self.pushButtonAceptar.setGeometry(QtCore.QRect(360, 360, 93, 28))
        self.pushButtonAceptar.setObjectName("pushButtonAceptar")
        self.textEditRespuesta = QtWidgets.QTextEdit(DialogInsertar)
        self.textEditRespuesta.setGeometry(QtCore.QRect(480, 90, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEditRespuesta.setFont(font)
        self.textEditRespuesta.setObjectName("textEditRespuesta")
        self.label_6 = QtWidgets.QLabel(DialogInsertar)
        self.label_6.setGeometry(QtCore.QRect(220, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.pushButtonLimpiar.clicked.connect(self.limpiar)
        self.pushButtonAceptar.clicked.connect(self.aceptar)

        self.retranslateUi(DialogInsertar)
        QtCore.QMetaObject.connectSlotsByName(DialogInsertar)

    def retranslateUi(self, DialogInsertar):
        _translate = QtCore.QCoreApplication.translate
        DialogInsertar.setWindowTitle(_translate("DialogInsertar", "Víctor Luque - PyQT5 - Insertar Dato"))
        self.label.setText(_translate("DialogInsertar", "Sepal Length (cm):"))
        self.label_3.setText(_translate("DialogInsertar", "Petal Length (cm):"))
        self.label_4.setText(_translate("DialogInsertar", "Petal Width (cm):"))
        self.label_5.setText(_translate("DialogInsertar", "Species:"))
        self.label_2.setText(_translate("DialogInsertar", "Sepal Width (cm):"))
        self.pushButtonLimpiar.setText(_translate("DialogInsertar", "Limpiar"))
        self.pushButtonAceptar.setText(_translate("DialogInsertar", "Aceptar"))
        self.textEditRespuesta.setHtml(_translate("DialogInsertar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">{}</span></p></body></html>"))
        self.label_6.setText(_translate("DialogInsertar", "Insertar Nuevo Registro"))

    def limpiar(self):
        self.spinBoxPTL.setValue(0)
        self.spinBoxPTW.setValue(0)
        self.spinBoxSPL.setValue(0)
        self.spinBoxSPW.setValue(0)
        self.lineEditSpecies.clear()
        self.textEditRespuesta.clear()
        self.textEditRespuesta.setText("{}")

    def aceptar(self):
        sepal_length = self.spinBoxSPL.value()
        sepal_width = self.spinBoxSPW.value()
        petal_length = self.spinBoxPTL.value()
        petal_width = self.spinBoxPTW.value()
        species = self.lineEditSpecies.text()
        data = {
            'sepal_length': sepal_length,
            'sepal_width': sepal_width,
            'petal_length': petal_length,
            'petal_width': petal_width,
            'species': species
        }
        iris = RestIris()
        response = json.dumps(iris.post_data(data), indent=4)
        self.textEditRespuesta.setText(response)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogInsertar = QtWidgets.QDialog()
    ui = Ui_DialogInsertar()
    ui.setupUi(DialogInsertar)
    DialogInsertar.show()
    sys.exit(app.exec_())
