# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\gui\template\precision.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from app import RestIris

class Ui_DialogPrecision(object):
    def setupUi(self, DialogPrecision):
        DialogPrecision.setObjectName("DialogPrecision")
        DialogPrecision.resize(640, 298)
        self.gridLayoutWidget = QtWidgets.QWidget(DialogPrecision)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelResultadoDTC = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelResultadoDTC.setFont(font)
        self.labelResultadoDTC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResultadoDTC.setObjectName("labelResultadoDTC")
        self.gridLayout.addWidget(self.labelResultadoDTC, 0, 0, 1, 1)
        self.labelResultadoRFC = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelResultadoRFC.setFont(font)
        self.labelResultadoRFC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResultadoRFC.setObjectName("labelResultadoRFC")
        self.gridLayout.addWidget(self.labelResultadoRFC, 0, 1, 1, 1)
        self.labelPrecisionDTC = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPrecisionDTC.setFont(font)
        self.labelPrecisionDTC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecisionDTC.setObjectName("labelPrecisionDTC")
        self.gridLayout.addWidget(self.labelPrecisionDTC, 1, 0, 1, 1)
        self.labelPrecisionRFC = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPrecisionRFC.setFont(font)
        self.labelPrecisionRFC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecisionRFC.setObjectName("labelPrecisionRFC")
        self.gridLayout.addWidget(self.labelPrecisionRFC, 1, 1, 1, 1)

        self.retranslateUi(DialogPrecision)
        QtCore.QMetaObject.connectSlotsByName(DialogPrecision)

    def retranslateUi(self, DialogPrecision):
        iris = RestIris()
        dtc, rfc = iris.get_accuracy()["algorithms"]
        _translate = QtCore.QCoreApplication.translate
        DialogPrecision.setWindowTitle(_translate("DialogPrecision", "Víctor Luque - PyQT5 - Precisión "))
        self.labelResultadoDTC.setText(_translate("DialogPrecision", "Decission Tree Classifier"))
        self.labelResultadoRFC.setText(_translate("DialogPrecision", "Random Forest Classifier"))
        self.labelPrecisionDTC.setText(_translate("DialogPrecision", dtc["results"]["accuracy"]))
        self.labelPrecisionRFC.setText(_translate("DialogPrecision", rfc["results"]["accuracy"]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogPrecision = QtWidgets.QDialog()
    ui = Ui_DialogPrecision()
    ui.setupUi(DialogPrecision)
    DialogPrecision.show()
    sys.exit(app.exec_())
