# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\gui\template\predecir.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from app import RestIris
import json

class Ui_DialogPredecir(object):
    def setupUi(self, DialogPredecir):
        DialogPredecir.setObjectName("DialogPredecir")
        DialogPredecir.resize(706, 424)
        self.label_7 = QtWidgets.QLabel(DialogPredecir)
        self.label_7.setGeometry(QtCore.QRect(220, 30, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayoutWidget_2 = QtWidgets.QWidget(DialogPredecir)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 451, 251))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setVerticalSpacing(15)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinBoxSPL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPL.setFont(font)
        self.spinBoxSPL.setObjectName("spinBoxSPL")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPL)
        self.spinBoxSPW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxSPW.setFont(font)
        self.spinBoxSPW.setObjectName("spinBoxSPW")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxSPW)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBoxPTL = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTL.setFont(font)
        self.spinBoxPTL.setObjectName("spinBoxPTL")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTL)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBoxPTW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxPTW.setFont(font)
        self.spinBoxPTW.setObjectName("spinBoxPTW")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxPTW)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEditClassifier = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditClassifier.setFont(font)
        self.lineEditClassifier.setObjectName("lineEditSpecies")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditClassifier)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.pushButtonAceptar = QtWidgets.QPushButton(DialogPredecir)
        self.pushButtonAceptar.setGeometry(QtCore.QRect(380, 370, 93, 28))
        self.pushButtonAceptar.setObjectName("pushButtonAceptar")
        self.pushButtonLimpiar = QtWidgets.QPushButton(DialogPredecir)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(270, 370, 93, 28))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.label = QtWidgets.QLabel(DialogPredecir)
        self.label.setGeometry(QtCore.QRect(20, 360, 221, 61))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.textEditRespuesta = QtWidgets.QTextEdit(DialogPredecir)
        self.textEditRespuesta.setGeometry(QtCore.QRect(490, 110, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEditRespuesta.setFont(font)
        self.textEditRespuesta.setObjectName("textEditRespuesta")

        self.pushButtonAceptar.clicked.connect(self.predecir)
        self.pushButtonLimpiar.clicked.connect(self.limpiar)

        self.retranslateUi(DialogPredecir)
        QtCore.QMetaObject.connectSlotsByName(DialogPredecir)

    def limpiar(self):
        self.lineEditClassifier.clear()
        self.spinBoxSPL.setValue(0)
        self.spinBoxSPW.setValue(0)
        self.spinBoxPTL.setValue(0)
        self.spinBoxPTW.setValue(0)
        self.textEditRespuesta.clear()
        self.textEditRespuesta.setText("{}")

    def predecir(self):
        classifier = self.lineEditClassifier.text()
        spl = float(self.spinBoxSPL.value())
        spw = float(self.spinBoxSPW.value())
        ptl = float(self.spinBoxPTL.value())
        ptw = float(self.spinBoxPTW.value())
        data = {
            'classifier': classifier, 
            'sepal_length': spl, 
            'sepal_width': spw,
            'petal_length': ptl,
            'petal_width': ptw
        }
        iris = RestIris()
        response = iris.post_predict(data)
        self.textEditRespuesta.setText(json.dumps(response, indent=4))



    def retranslateUi(self, DialogPredecir):
        _translate = QtCore.QCoreApplication.translate
        DialogPredecir.setWindowTitle(_translate("DialogPredecir", "Víctor Luque - PyQT5 - Predecir Dato"))
        self.label_7.setText(_translate("DialogPredecir", "Predecir Nuevo Registro"))
        self.label_8.setText(_translate("DialogPredecir", "Sepal Length (cm):"))
        self.label_9.setText(_translate("DialogPredecir", "Petal Length (cm):"))
        self.label_10.setText(_translate("DialogPredecir", "Petal Width (cm):"))
        self.label_11.setText(_translate("DialogPredecir", "Modelo:"))
        self.label_12.setText(_translate("DialogPredecir", "Sepal Width (cm):"))
        self.pushButtonAceptar.setText(_translate("DialogPredecir", "Aceptar"))
        self.pushButtonLimpiar.setText(_translate("DialogPredecir", "Limpiar"))
        self.label.setText(_translate("DialogPredecir", "Nota: El modelo debe ser DecissionTree o RandomForest"))
        self.textEditRespuesta.setHtml(_translate("DialogPredecir", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">{}</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogPredecir = QtWidgets.QDialog()
    ui = Ui_DialogPredecir()
    ui.setupUi(DialogPredecir)
    DialogPredecir.show()
    sys.exit(app.exec_())
